on: push

env:
  clientId: 00000000-0000-0000-0000-000000000000
  tenant: your-tenant.onmicrosoft.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get files
      uses: actions/checkout@v2

    - id: aadgraph-login
      name: Adquiring AAD graph Access Token
      uses: Azure/azure-resource-login-action@v1.0.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-type-name: AadGraph
 
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1.2.0
      with:
        inlineScript: Get-AzureADMSNamedLocationPolicy
        # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
        azPSVersion: latest
   
    - id: write-log
      name: Write Token to Console
      run: echo ${{ steps.aadgraph-login.outputs.token }}
