on: push

env:
  clientId: 00000000-0000-0000-0000-000000000000
  tenant: your-tenant.onmicrosoft.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get files
      uses: actions/checkout@v2

    - id: aadgraph-login
      name: Adquiring AAD graph Access Token
      uses: Azure/azure-resource-login-action@v1.0.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-type-name: AadGraph
 
    - id: write-log
      name: Write Token to Console
      run: echo ${{ steps.aadgraph-login.outputs.token }}
